# Generated by Django 3.2.13 on 2022-05-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddata',
            name='specific_id',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='date',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
