# Generated by Django 3.2.13 on 2022-05-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0002_auto_20220515_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.CharField(max_length=8)),
                ('finishdate', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='BoardData',
        ),
    ]
