# Generated by Django 3.2.13 on 2022-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0003_auto_20220517_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField()),
            ],
        ),
    ]
