# Generated by Django 3.2.13 on 2022-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0004_boarddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='finish',
            field=models.CharField(max_length=10, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='start',
            field=models.CharField(max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
