# Generated by Django 3.2.13 on 2022-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0005_auto_20220518_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarddata',
            old_name='title',
            new_name='title1',
        ),
        migrations.RemoveField(
            model_name='boarddata',
            name='link',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='link1',
            field=models.URLField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='link2',
            field=models.URLField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='link3',
            field=models.URLField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='title2',
            field=models.CharField(max_length=300, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='title3',
            field=models.CharField(max_length=300, null='True'),
            preserve_default='True',
        ),
    ]
