# Generated by Django 3.2.13 on 2022-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0006_auto_20220519_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddata',
            name='title1',
            field=models.CharField(max_length=300, null='True'),
        ),
    ]
