# Generated by Django 3.2.13 on 2022-05-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0007_alter_boarddata_title1'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='cloud',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
