# Generated by Django 3.2.13 on 2022-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0008_boarddata_cloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=300, null='True')),
                ('url', models.URLField(null='True')),
            ],
        ),
    ]
