# Generated by Django 3.2.13 on 2022-05-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0009_crawldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddata',
            name='word1',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='word2',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='boarddata',
            name='word3',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
    ]
